import { Tool, ToolGroup } from '../types';

export const TOOL_GROUPS: ToolGroup[] = [
  {
    id: 'media',
    name: 'Grup Gambar & Media',
    description: 'Edit, kompres, konversi, dan lindungi foto serta video Anda secara instan.',
    iconName: 'Camera',
  },
  {
    id: 'admin',
    name: 'Grup Administrasi & Instansi',
    description: 'Urus surat menyurat, PDF, cetak label undangan, dan validasi kepegawaian.',
    iconName: 'FileText',
  },
  {
    id: 'bisnis',
    name: 'Grup Duit & Bisnis UMKM',
    description: 'Kalkulator keuangan, hitung potongan admin toko online, HPP, serta QR Code.',
    iconName: 'Wallet',
  },
  {
    id: 'sosial',
    name: 'Grup Komunitas & Sosial Lokal',
    description: 'Alat penunjang aktivitas warga, jadwal sholat, font unik, dan kalkulator lokal.',
    iconName: 'Users',
  },
];

export const TOOLS: Tool[] = [
  // --- MEDIA ---
  {
    id: 'watermark-ktp',
    name: 'Watermark KTP Anti-Pinjol',
    category: 'media',
    description: 'Tempel teks pengaman transparan pada foto KTP agar tidak disalahgunakan untuk pinjol ilegal.',
    badge: '🔒 100% Aman',
    iconName: 'ShieldAlert',
    reverseOf: 'redaktur-ktp',
  },
  {
    id: 'redaktur-ktp',
    name: 'Sensor Data KTP (Redaktur KTP)',
    category: 'media',
    description: 'Kebalikan Watermark: Sensor atau buramkan tanda tangan, foto wajah, atau nomor NIK KTP Anda untuk privasi.',
    badge: '🛡️ Privasi Pro',
    iconName: 'EyeOff',
    reverseOf: 'watermark-ktp',
  },
  {
    id: 'word-to-jpg',
    name: 'Ubah Word Jadi Gambar JPG',
    category: 'media',
    description: 'Buat draf tulisan dokumen rapi dan ekspor jadi gambar JPG bersih agar bisa langsung disebar di WhatsApp.',
    iconName: 'FileSpreadsheet',
    reverseOf: 'image-to-word',
  },
  {
    id: 'image-to-word',
    name: 'Ekstrak Gambar ke Word (.docx)',
    category: 'media',
    description: 'Kebalikan: Kumpulkan beberapa foto/gambar hasil jepretan Anda, lalu kemas menjadi file Word (.docx) siap cetak.',
    iconName: 'FileWord',
    reverseOf: 'word-to-jpg',
  },
  {
    id: 'kompres-video',
    name: 'Kompresor Video WA Pas 16MB',
    category: 'media',
    description: 'Mengecilkan resolusi video besar agar muat dikirim utuh tanpa terpotong batas maksimal WA (16MB).',
    iconName: 'Video',
    reverseOf: 'video-splitter',
  },
  {
    id: 'video-splitter',
    name: 'Pemotong Video Status WA per 30 Detik',
    category: 'media',
    description: 'Solusi Alternatif: Potong otomatis video panjang menjadi bagian-bagian kecil 30 detik untuk Status WhatsApp.',
    badge: '🎬 Sangat Praktis',
    iconName: 'Scissors',
    reverseOf: 'kompres-video',
  },
  {
    id: 'pasfoto-cpns',
    name: 'Pasfoto CPNS & Kerja Instan',
    category: 'media',
    description: 'Ubah ukuran, crop wajah, dan ganti warna latar belakang (merah/biru) pasfoto pendaftaran kerja.',
    iconName: 'UserCheck',
    reverseOf: 'pasfoto-grid',
  },
  {
    id: 'pasfoto-grid',
    name: 'Pembuat Grid Cetak Pasfoto',
    category: 'media',
    description: 'Kebalikan: Tata pasfoto Anda ke dalam lembar cetak grid ukuran 2x3, 3x4, dan 4x6 siap cetak di kertas A4.',
    iconName: 'Grid',
    reverseOf: 'pasfoto-cpns',
  },
  {
    id: 'konversi-webp',
    name: 'Pengubah Gambar (WebP <=> JPG/PNG)',
    category: 'media',
    description: 'Ubah foto produk ke format WebP agar website toko online ringan, atau sebaliknya secepat kilat.',
    iconName: 'RefreshCw',
    reverseOf: 'bulk-compress-image',
  },
  {
    id: 'bulk-compress-image',
    name: 'Kompresor Gambar Massal',
    category: 'media',
    description: 'Kebalikan: Kecilkan ukuran file (KB) puluhan gambar sekaligus dengan mengatur kualitas persen tanpa mengubah format.',
    iconName: 'Minimize2',
    reverseOf: 'konversi-webp',
  },
  {
    id: 'watermark-massal',
    name: 'Watermark Gambar Massal',
    category: 'media',
    description: 'Pasang nama toko, nomor HP, atau logo jualanmu ke banyak foto produk sekaligus agar anti-maling.',
    iconName: 'Copy',
    reverseOf: 'exif-cleaner',
  },
  {
    id: 'exif-cleaner',
    name: 'Pembersih Metadata Foto (Exif Cleaner)',
    category: 'media',
    description: 'Kebalikan: Hapus rahasia lokasi GPS, tipe HP, dan tanggal pengambilan dari file foto Anda sebelum dibagikan.',
    badge: '🕵️ Anti-Lacak',
    iconName: 'Trash2',
    reverseOf: 'watermark-massal',
  },
  {
    id: 'subtitle-generator',
    name: 'Subtitle Video AI Otomatis & Transkrip Suara (SRT/VTT)',
    category: 'media',
    description: 'Unggah video asli: sistem mendengarkan suara & mendeteksi percakapan otomatis (Speech-to-Text), live subtitle sync gaya TikTok/CapCut, dan ekspor SRT/VTT.',
    badge: '🎬 AI Voice Pro',
    iconName: 'Clapperboard',
  },
  {
    id: 'remove-bg',
    name: 'Hapus Background Gambar Instan',
    category: 'media',
    description: 'Hapus warna latar belakang foto produk jualan Anda secara otomatis langsung di browser tanpa upload data.',
    badge: '✂️ Efek Transparan',
    iconName: 'Layers',
  },

  // --- ADMIN ---
  {
    id: 'kompres-pdf',
    name: 'Kompres PDF Target 200KB/500KB',
    category: 'admin',
    description: 'Kecilkan ukuran file ijazah atau dokumen pendaftaran pns/kerja agar lolos batas maksimal upload sistem online.',
    iconName: 'FileArchive',
    reverseOf: 'pdf-merger',
  },
  {
    id: 'pdf-merger',
    name: 'Penggabung & Pemecah PDF',
    category: 'admin',
    description: 'Kebalikan: Gabungkan beberapa file PDF menjadi satu, atau pecah dokumen PDF panjang menjadi lembaran terpisah.',
    badge: '🧩 Serbaguna',
    iconName: 'Columns',
    reverseOf: 'kompres-pdf',
  },
  {
    id: 'pdf-to-jpg',
    name: 'Ubah PDF Jadi Gambar JPG',
    category: 'admin',
    description: 'Konversi setiap halaman dokumen PDF menjadi kumpulan gambar JPG utuh secara instan.',
    iconName: 'FileImage',
    reverseOf: 'jpg-to-pdf',
  },
  {
    id: 'jpg-to-pdf',
    name: 'Ubah Gambar JPG Jadi PDF',
    category: 'admin',
    description: 'Kebalikan: Ubah satu atau banyak foto jepretan dokumen (JPG/PNG) menjadi satu file dokumen PDF siap kirim.',
    iconName: 'FileDown',
    reverseOf: 'pdf-to-jpg',
  },
  {
    id: 'ekstrak-pdf',
    name: 'Ekstrak Teks & Gambar PDF',
    category: 'admin',
    description: 'Ambil ketikan teks asli dan selamatkan gambar yang ada di dalam file PDF tanpa merusak berkas.',
    iconName: 'SearchCode',
    reverseOf: 'text-to-pdf',
  },
  {
    id: 'text-to-pdf',
    name: 'Teks Jadi PDF (Text-to-PDF)',
    category: 'admin',
    description: 'Kebalikan: Ketik atau copas teks biasa, lalu unduh dalam format dokumen PDF rapi dengan sekali klik.',
    iconName: 'FilePlus',
    reverseOf: 'ekstrak-pdf',
  },
  {
    id: 'generator-surat',
    name: 'Generator Surat Resmi & Izin Sakit',
    category: 'admin',
    description: 'Isi formulir singkat, sistem otomatis membuat draf surat resmi, lamaran kerja, atau izin sakit siap cetak.',
    iconName: 'PenTool',
    reverseOf: 'digital-signature',
  },
  {
    id: 'digital-signature',
    name: 'Pembuat Tanda Tangan & Cap Digital',
    category: 'admin',
    description: 'Kebalikan: Gambar tanda tangan atau cap Anda di layar HP, buat latar belakang transparan, lalu unduh sebagai file PNG.',
    badge: '🖊️ Transparan PNG',
    iconName: 'FileSignature',
    reverseOf: 'generator-surat',
  },
  {
    id: 'label-103',
    name: 'Cetak Label Undangan 103',
    category: 'admin',
    description: 'Ketik nama-nama tamu undangan, cetak pas presisi pada kertas label nomor undian/undangan 103.',
    iconName: 'Printer',
    reverseOf: 'label-121',
  },
  {
    id: 'label-121',
    name: 'Cetak Label Kode/Undangan 121',
    category: 'admin',
    description: 'Kebalikan: Cetak nama atau kode barang pada ukuran label 121 yang lebih kecil untuk penomoran inventaris.',
    iconName: 'Tags',
    reverseOf: 'label-103',
  },
  {
    id: 'pemecah-nip',
    name: 'Validasi & Pemecah Kode NIP PNS',
    category: 'admin',
    description: 'Masukkan NIP PNS, sistem otomatis memvalidasi keaslian serta membaca tanggal lahir, jenis kelamin, dan tanggal angkat.',
    iconName: 'BadgeInfo',
    reverseOf: 'nip-generator',
  },
  {
    id: 'nip-generator',
    name: 'PNS NIP Generator Otomatis',
    category: 'admin',
    description: 'Kebalikan: Masukkan data tanggal lahir, tanggal mulai bekerja sebagai PNS, dan urutan kelulusan untuk membuat susunan kode NIP yang valid.',
    iconName: 'Fingerprint',
    reverseOf: 'pemecah-nip',
  },
  {
    id: 'ocr-scan',
    name: 'Scan Foto Dokumen Jadi Teks (OCR)',
    category: 'admin',
    description: 'Foto berkas fisik, buku, atau nota jualan Anda, lalu ambil tulisan ketikannya secara otomatis untuk disalin.',
    badge: '📷 Ambil Teks',
    iconName: 'ScanText',
    reverseOf: 'text-to-speech',
  },
  {
    id: 'text-to-speech',
    name: 'Suara Google Bahasa Indonesia (TTS)',
    category: 'admin',
    description: 'Kebalikan: Ketik kata-kata atau teks panjang, dengarkan pengucapannya, atau unduh sebagai rekaman audio MP3 gratis.',
    iconName: 'Volume2',
    reverseOf: 'ocr-scan',
  },
  {
    id: 'hitung-umur',
    name: 'Hitung Presisi Umur & Masa Kerja',
    category: 'admin',
    description: 'Hitung presisi berapa tahun, bulan, dan hari sisa usia Anda atau total masa bakti pengabdian kerja.',
    iconName: 'CalendarDays',
    reverseOf: 'pensiun-countdown',
  },
  {
    id: 'pensiun-countdown',
    name: 'Kalkulator Masa Pensiun PNS',
    category: 'admin',
    description: 'Kebalikan: Masukkan tanggal lahir dan batas usia pensiun untuk menghitung tanggal pensiun serta sisa masa aktif kerja.',
    iconName: 'Hourglass',
    reverseOf: 'hitung-umur',
  },
  {
    id: 'word-counter',
    name: 'Penghitung Kata & Karakter Pro (Word Counter)',
    category: 'admin',
    description: 'Hitung total kata, huruf, kalimat, paragraf, estimasi waktu baca, serta kepadatan kata kunci dalam artikel Anda.',
    badge: '✍️ SEO Writer',
    iconName: 'FileText',
  },

  // --- BISNIS ---
  {
    id: 'potongan-admin',
    name: 'Kalkulator Potongan Admin Toko',
    category: 'bisnis',
    description: 'Hitung bersih uang yang diterima seller dari Shopee, Tokopedia, TikTok Shop, & Lazada setelah komisi.',
    iconName: 'Calculator',
    reverseOf: 'target-pricing',
  },
  {
    id: 'target-pricing',
    name: 'Kalkulator Harga Jual Target Profit',
    category: 'bisnis',
    description: 'Kebalikan: Hitung harga jual yang harus dipasang di Shopee/TikTok agar Anda tetap mendapat profit bersih yang ditargetkan.',
    badge: '💡 Profit Aman',
    iconName: 'TrendingUp',
    reverseOf: 'potongan-admin',
  },
  {
    id: 'kalkulator-hpp',
    name: 'Kalkulator HPP UMKM',
    category: 'bisnis',
    description: 'Hitung harga pokok produksi warung, toko roti, atau grosir agar tidak rugi dalam menentukan dasar harga.',
    iconName: 'TrendingDown',
    reverseOf: 'bep-calculator',
  },
  {
    id: 'bep-calculator',
    name: 'Kalkulator Break-Even Point (BEP)',
    category: 'bisnis',
    description: 'Kebalikan: Hitung batas penjualan minimum atau jumlah unit jualan yang harus laku agar modal usaha Anda kembali (balik modal).',
    iconName: 'Target',
    reverseOf: 'kalkulator-hpp',
  },
  {
    id: 'qr-tool',
    name: 'Pembuat QR Code & Scan Galeri',
    category: 'bisnis',
    description: 'Buat barcode QR tokomu sendiri atau scan isi file QR code kiriman orang langsung dari galeri HP.',
    iconName: 'QrCode',
    reverseOf: 'barcode-tool',
  },
  {
    id: 'barcode-tool',
    name: 'Generator & Reader Barcode Toko',
    category: 'bisnis',
    description: 'Kebalikan: Buat barcode garis (EAN-13 / Code 128) untuk label harga produk fisik Anda di kasir, atau baca kodenya.',
    iconName: 'Barcode',
    reverseOf: 'qr-tool',
  },
  {
    id: 'link-bio',
    name: 'Link Bio Brosur Sederhana (Linktree Lokal)',
    category: 'bisnis',
    description: 'Buat satu link halaman bio cantik berisi katalog produk, medsos, WA, dan maps untuk profil Instagram/TikTok UMKM Anda.',
    badge: '🔗 Branding UMKM',
    iconName: 'Link',
  },
  {
    id: 'nota-extractor',
    name: 'Ekstraktor Foto Nota ke Excel / CSV',
    category: 'bisnis',
    description: 'Foto nota belanja atau kwitansi tulisan tangan Anda, lalu ekstrak otomatis jadi baris tabel barang dan unduh sebagai file Excel (CSV) secara gratis.',
    badge: '📸 Foto ke Excel',
    iconName: 'FileSpreadsheet',
  },

  // --- SOSIAL ---
  {
    id: 'jadwal-sholat',
    name: 'Jadwal Salat Digital Masjid',
    category: 'sosial',
    description: 'Hitung jadwal sholat bulanan otomatis sesuai garis lintang dan bujur koordinat desa Anda untuk dicetak atau layar TV masjid.',
    iconName: 'BookmarkCheck',
    reverseOf: 'qibla-compass',
  },
  {
    id: 'qibla-compass',
    name: 'Kompas Arah Kiblat Online',
    category: 'sosial',
    description: 'Kebalikan: Temukan arah kiblat Ka\'bah yang presisi dari lokasi masjid Anda menggunakan sensor GPS HP Anda secara langsung.',
    badge: '🧭 Akurat GPS',
    iconName: 'Navigation',
    reverseOf: 'jadwal-sholat',
  },
  {
    id: 'font-aesthetic',
    name: 'Tulisan Unik Sosmed (Aesthetic)',
    category: 'sosial',
    description: 'Ubah ketikan biasa menjadi teks tebal, miring, latin meliuk-liuk unik untuk dipasang di bio jualan WA atau caption TikTok.',
    iconName: 'Smile',
    reverseOf: 'font-normalizer',
  },
  {
    id: 'font-normalizer',
    name: 'Pembersih Font Unik (Normalizer)',
    category: 'sosial',
    description: 'Kebalikan: Ubah tulisan aneh/lebay sosmed kiriman orang lain menjadi teks alfabet latin biasa yang mudah dibaca.',
    iconName: 'Sparkles',
    reverseOf: 'font-aesthetic',
  },
  {
    id: 'selamatan-jawa',
    name: 'Kalkulator Selamatan Kematian',
    category: 'sosial',
    description: 'Hitung otomatis tanggal dan penanggalan adat jawa untuk peringatan kematian: 3 hari, 7 hari, 40 hari, 100 hari, mendak, dan 1000 hari.',
    badge: '🕌 Budaya Lokal',
    iconName: 'CalendarHeart',
  },
  {
    id: 'text-repeater',
    name: 'Repeater & Pengganda Teks Massal',
    category: 'sosial',
    description: 'Ulangi atau gandakan suatu kata/kalimat hingga ribuan kali dengan pembatas baris baru/spasi secara kilat untuk pesan WhatsApp.',
    badge: '🔁 Kirim Kilat',
    iconName: 'RefreshCw',
  },
];
